src/Entity/Societe.php
<?php

namespace App\Entity;

use App\Repository\SocieteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SocieteRepository::class)]
class Societe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $logo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    private ?string $tel = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_contact = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $commentaires = null;

    #[ORM\OneToMany(mappedBy: 'societe', targetEntity: Users::class)]
    private Collection $users;

    #[ORM\OneToMany(mappedBy: 'societe', targetEntity: Missions::class)]
    private Collection $missions;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): static
    {
        $this->tel = $tel;

        return $this;
    }

    public function getNomContact(): ?string
    {
        return $this->nom_contact;
    }

    public function setNomContact(?string $nom_contact): static
    {
        $this->nom_contact = $nom_contact;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): static
    {
        $this->website = $website;

        return $this;
    }

    public function getCommentaires(): ?string
    {
        return $this->commentaires;
    }

    public function setCommentaires(?string $commentaires): static
    {
        $this->commentaires = $commentaires;

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Users $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setSociete($this);
        }

        return $this;
    }

    public function removeUser(Users $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSociete() === $this) {
                $user->setSociete(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Missions>
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Missions $mission): static
    {
        if (!$this->missions->contains($mission)) {
            $this->missions->add($mission);
            $mission->setSociete($this);
        }

        return $this;
    }

    public function removeMission(Missions $mission): static
    {
        if ($this->missions->removeElement($mission)) {
            // set the owning side to null (unless already changed)
            if ($mission->getSociete() === $this) {
                $mission->setSociete(null);
            }
        }

        return $this;
    }
}

src/Form/SocieteType.php
<?php

namespace App\Form;

use App\Entity\Societe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SocieteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', null, [
                'label' => 'Nom',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('logo', null, [
                'label' => 'logo',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('adresse', null, [
                'label' => 'Adresse',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('code_postal', null, [
                'label' => 'Code postal',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('ville', null, [
                'label' => 'Ville',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('tel', null, [
                'label' => 'Téléphone',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('nom_contact', null, [
                'label' => 'Nom du contact',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('email', null, [
                'label' => 'Email',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('website', null, [
                'label' => 'Site web',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
            ->add('commentaires', null, [
                'label' => 'Commentaires à afficher pour les TC',
                'attr' => array(
                    'class' => 'form-control mb-1'
                )                
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Societe::class,
        ]);
    }
}

src/Controller/SocieteController.php
<?php

namespace App\Controller;

use App\Entity\Societe;
use App\Form\SocieteType;
use App\Repository\SocieteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/societe')]
class SocieteController extends AbstractController
{
    #[Route('/', name: 'app_societe_index', methods: ['GET'])]
    public function index(SocieteRepository $societeRepository): Response
    {
        return $this->render('societe/index.html.twig', [
            'societes' => $societeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_societe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SocieteRepository $societeRepository): Response
    {
        $societe = new Societe();
        $form = $this->createForm(SocieteType::class, $societe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $societeRepository->save($societe, true);

            return $this->redirectToRoute('app_societe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('societe/new.html.twig', [
            'societe' => $societe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_societe_show', methods: ['GET'])]
    public function show(Societe $societe): Response
    {
        return $this->render('societe/show.html.twig', [
            'societe' => $societe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_societe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Societe $societe, SocieteRepository $societeRepository): Response
    {
        $form = $this->createForm(SocieteType::class, $societe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $societeRepository->save($societe, true);

            return $this->redirectToRoute('app_societe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('societe/edit.html.twig', [
            'societe' => $societe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_societe_delete', methods: ['POST'])]
    public function delete(Request $request, Societe $societe, SocieteRepository $societeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$societe->getId(), $request->request->get('_token'))) {
            $societeRepository->remove($societe, true);
        }

        return $this->redirectToRoute('app_societe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/societe/_delete_form.html.twig
<form method="post" action="{{ path('app_societe_delete', {'id': societe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ societe.id) }}">
    <button class="btn btn-lg btn-violet d-grid gap-2 w-100 mx-auto">Supprimer la société</button>
</form>

templates/societe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Societe{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-8 mx-auto"> 
            <h1>{{ societe.nom }}</h1>
            {{ form_errors(form) }}
            {{ form_start(form, {'attr': {'class': 'my-2'}}) }}
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(form.nom) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.logo) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.adresse) }}
                    </div>
                    <div class="col-md-2">
                        {{ form_row(form.code_postal) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.ville) }}
                    </div>
                    <div class="col-md-5">
                        {{ form_row(form.nom_contact) }}
                    </div>
                    <div class="col-md-3">
                    {{ form_row(form.tel) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.email) }}
                    </div>
                </div>
                {{ form_rest(form) }}
                <button type="submit" class="btn btn-lg btn-green d-grid gap-2 w-100">Enregistrer les modifications</button>
                <a href="{{ path('app_societe_index') }}" class="btn btn-lg btn-bleu d-grid gap-2 col-12 mx-auto my-2">Retour à la liste des sociétés</a>
                
            {{ form_end(form) }}
            {{ include('societe/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/societe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Societe index{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center"><a href="{{ path('app_societe_new') }}" class="btn btn-lg btn-green m-2">Ajouter une société</a><a href="{{ path('app_users') }}" class="btn btn-lg btn-orange m-2">Retour aux utilisateurs</a></div>
    <h1 class="text-center">Liste des Sociétés</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Ville</th>
                <th>Tel</th>
                <th>Nom_contact</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for societe in societes %}
            <tr>
                <td>{{ societe.id }}</td>
                <td>{{ societe.nom }}</td>
                <td>{{ societe.ville }}</td>
                <td>{{ societe.tel }}</td>
                <td>{{ societe.nomContact }}</td>
                <td>{{ societe.email }}</td>
                <td>
                    <a href="{{ path('app_societe_show', {'id': societe.id}) }}" class="btn btn-green"><i class="fa-solid fa-magnifying-glass"></i> Voir plus</a>
                    <a href="{{ path('app_societe_edit', {'id': societe.id}) }}" class="btn btn-bleu">Modifier</
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/societe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Societe{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center"><a class="btn btn-lg btn-bleu my-2 mx-auto" href="{{ path('app_societe_index') }}"><i class="fa-solid fa-arrow-left"></i> Retour</a></div>
    <h1 class="text-center">Nouvelle Société</h1>

    {{ include('_partials/_form.html.twig') }}

{% endblock %}

templates/societe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Societe{% endblock %}

{% block body %}
    <h1>Societe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ societe.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ societe.nom }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ societe.logo }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ societe.adresse }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ societe.codePostal }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ societe.ville }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ societe.tel }}</td>
            </tr>
            <tr>
                <th>Nom_contact</th>
                <td>{{ societe.nomContact }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ societe.email }}</td>
            </tr>
            <tr>
                <th>Website</th>
                <td>{{ societe.website }}</td>
            </tr>
            <tr>
                <th>Commentaires</th>
                <td>{{ societe.commentaires }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{{ path('app_societe_index') }}" class="btn btn-lg btn-bleu d-grid gap-2 col-6 mx-auto my-2">Retour à la liste des sociétés</a>
    <a href="{{ path('app_societe_edit', {'id': societe.id}) }}" class="btn btn-lg btn-green d-grid gap-2 col-6 mx-auto my-2">Modifier</a>

    {{ include('societe/_delete_form.html.twig') }}
{% endblock %}