src/Entity/Missions.php
<?php

namespace App\Entity;

use App\Repository\MissionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MissionsRepository::class)]
class Missions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $script = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $commentaires = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $email_rdv_client_text = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $email_rdv_prospect_text = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fichier = null;

    #[ORM\ManyToMany(targetEntity: Users::class, inversedBy: 'missions')]
    private Collection $user;

    #[ORM\ManyToMany(targetEntity: Champs::class, inversedBy: 'missions')]
    private Collection $champs;

    #[ORM\ManyToMany(targetEntity: Statuts::class)]
    private Collection $statuts;

    #[ORM\ManyToMany(targetEntity: Prerempli::class)]
    private Collection $preremplis;

    #[ORM\ManyToOne(inversedBy: 'missions')]
    private ?Societe $societe = null;

    #[ORM\ManyToOne(inversedBy: 'missions')]
    private ?TypeMission $type = null;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->champs = new ArrayCollection();
        $this->statuts = new ArrayCollection();
        $this->preremplis = new ArrayCollection();
    }
    
    public function setId(): ?string
    {
        return $this->id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getScript(): ?string
    {
        return $this->script;
    }

    public function setScript(string $script): static
    {
        $this->script = $script;

        return $this;
    }

    public function getCommentaires(): ?string
    {
        return $this->commentaires;
    }

    public function setCommentaires(string $commentaires): static
    {
        $this->commentaires = $commentaires;

        return $this;
    }

    public function getEmailRdvClientText(): ?string
    {
        return $this->email_rdv_client_text;
    }

    public function setEmailRdvClientText(?string $email_rdv_client_text): static
    {
        $this->email_rdv_client_text = $email_rdv_client_text;

        return $this;
    }

    public function getEmailRdvProspectText(): ?string
    {
        return $this->email_rdv_prospect_text;
    }

    public function setEmailRdvProspectText(?string $email_rdv_prospect_text): static
    {
        $this->email_rdv_prospect_text = $email_rdv_prospect_text;

        return $this;
    }

    public function getFichier(): ?string
    {
        return $this->fichier;
    }

    public function setFichier(?string $fichier): static
    {
        $this->fichier = $fichier;

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(Users $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
        }

        return $this;
    }

    public function removeUser(Users $user): static
    {
        $this->user->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Champs>
     */
    public function getChamps(): Collection
    {
        return $this->champs;
    }

    public function addChamp(Champs $champ): static
    {
        if (!$this->champs->contains($champ)) {
            $this->champs->add($champ);
        }

        return $this;
    }

    public function removeChamp(Champs $champ): static
    {
        $this->champs->removeElement($champ);

        return $this;
    }

    /**
     * @return Collection<int, Statuts>
     */
    public function getStatuts(): Collection
    {
        return $this->statuts;
    }

    public function addStatut(Statuts $statut): static
    {
        if (!$this->statuts->contains($statut)) {
            $this->statuts->add($statut);
        }

        return $this;
    }

    public function removeStatut(Statuts $statut): static
    {
        $this->statuts->removeElement($statut);

        return $this;
    }

    /**
     * @return Collection<int, Prerempli>
     */
    public function getPreremplis(): Collection
    {
        return $this->preremplis;
    }

    public function addPrerempli(Prerempli $prerempli): static
    {
        if (!$this->preremplis->contains($prerempli)) {
            $this->preremplis->add($prerempli);
        }

        return $this;
    }

    public function removePrerempli(Prerempli $prerempli): static
    {
        $this->preremplis->removeElement($prerempli);

        return $this;
    }

    public function getSociete(): ?Societe
    {
        return $this->societe;
    }

    public function setSociete(?Societe $societe): static
    {
        $this->societe = $societe;

        return $this;
    }

    public function getType(): ?TypeMission
    {
        return $this->type;
    }

    public function setType(?TypeMission $type): static
    {
        $this->type = $type;

        return $this;
    }
}

src/Entity/Societe.php
<?php

namespace App\Entity;

use App\Repository\SocieteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SocieteRepository::class)]
class Societe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $logo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    private ?string $tel = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_contact = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $commentaires = null;

    #[ORM\OneToMany(mappedBy: 'societe', targetEntity: Users::class)]
    private Collection $users;

    #[ORM\OneToMany(mappedBy: 'societe', targetEntity: Missions::class)]
    private Collection $missions;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): static
    {
        $this->tel = $tel;

        return $this;
    }

    public function getNomContact(): ?string
    {
        return $this->nom_contact;
    }

    public function setNomContact(?string $nom_contact): static
    {
        $this->nom_contact = $nom_contact;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): static
    {
        $this->website = $website;

        return $this;
    }

    public function getCommentaires(): ?string
    {
        return $this->commentaires;
    }

    public function setCommentaires(?string $commentaires): static
    {
        $this->commentaires = $commentaires;

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(Users $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setSociete($this);
        }

        return $this;
    }

    public function removeUser(Users $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSociete() === $this) {
                $user->setSociete(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Missions>
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Missions $mission): static
    {
        if (!$this->missions->contains($mission)) {
            $this->missions->add($mission);
            $mission->setSociete($this);
        }

        return $this;
    }

    public function removeMission(Missions $mission): static
    {
        if ($this->missions->removeElement($mission)) {
            // set the owning side to null (unless already changed)
            if ($mission->getSociete() === $this) {
                $mission->setSociete(null);
            }
        }

        return $this;
    }
}

src/Controller/MissionsController.php
<?php

namespace App\Controller;

use App\Entity\Missions;
use App\Entity\Users;
use App\Form\MissionsType;
use App\Repository\MissionsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/missions')]
class MissionsController extends AbstractController
{
    #[Route('/', name: 'app_missions_index', methods: ['GET'])]
    public function index(MissionsRepository $missionsRepository): Response
    {
        return $this->render('missions/index.html.twig', [
            'missions' => $missionsRepository->findAll(),
        ]);
    }

    #[Route('/actuelles', name: 'app_missions_actuelles', methods: ['GET'])]
    public function actuel(MissionsRepository $missionsRepository): Response
    {
        $today = new \DateTime('now');
        // dd($today);
        return $this->render('missions/actuelles.html.twig', [
            'enquetes' => $missionsRepository->findEnqueteByActualDates($today),
            'prospections' => $missionsRepository->findProspectionByActualDates($today),
            'receptions' => $missionsRepository->findReceptionByActualDates($today),
        ]);
    }

    #[Route('/new', name: 'app_missions_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MissionsRepository $missionsRepository): Response
    {
        $mission = new Missions();
        $form = $this->createForm(MissionsType::class, $mission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $missionsRepository->save($mission, true);

            return $this->redirectToRoute('app_missions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('missions/new.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/show', name: 'app_missions_show', methods: ['GET'])]
    public function show(Missions $mission): Response
    {
        return $this->render('missions/show.html.twig', [
            'mission' => $mission,
        ]);
    }

    #[Route('/{id}/details', name: 'app_missions_details')]
    public function details(Missions $mission): Response
    {
        $user = $this->getUser();
        return $this->render('missions/details.html.twig', [
            'mission' => $mission,
            'user' => $user
        ]);
    }

    #[Route('/{id}/edit', name: 'app_missions_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Missions $mission, MissionsRepository $missionsRepository): Response
    {
        $form = $this->createForm(MissionsType::class, $mission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $missionsRepository->save($mission, true);

            return $this->redirectToRoute('app_missions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('missions/edit.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }
    #[Route('/{id}/duplicate', name: 'app_missions_duplicate', methods: ['GET', 'POST'])]
    public function duplicate(Request $request, Missions $mission, MissionsRepository $missionsRepository): Response
    {
        $duplicate = new Missions();
        $duplicate = clone $mission;
        $duplicate->setId(null);
        $form = $this->createForm(MissionsType::class, $duplicate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $missionsRepository->save($duplicate, true);

            return $this->redirectToRoute('app_missions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('missions/new.html.twig', [
            'mission' => $duplicate,
            'form' => $form,
        ]);

        return $this->redirectToRoute('app_missions_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_missions_delete', methods: ['POST'])]
    public function delete(Request $request, Missions $mission, MissionsRepository $missionsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$mission->getId(), $request->request->get('_token'))) {
            $missionsRepository->remove($mission, true);
        }

        return $this->redirectToRoute('app_missions_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/missions/_delete_form.html.twig
<form method="post" action="{{ path('app_missions_delete', {'id': mission.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cette mission?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mission.id) }}">
    <button class="btn btn-lg btn-violet d-grid gap-2 col-6 mx-auto">Supprimer la mission</button>
</form>

templates/missions/actuelles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Missions{% endblock %}

{% block body %}
    <h1 class="text-center">Missions en cours</h1>
    <div class="row">
        <!-- RECEPTION -->
        <div class="col-md-4">
            <h2>Réceptions</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Société</th>
                        <th>Mission</th>
                    </tr>
                </thead>
                <tbody>
                {% for mission in receptions %}
                    <tr>
                        <td>{{ mission.societe.nom }}</td>
                        <td><a href="{{ path('app_missions_details', {'id': mission.id}) }}">{{ mission.titre }}</a></td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="13">Aucune information trouvée</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div> <!-- /col-4 -->
        <!-- PROSPECTION -->
        <div class="col-md-4">
            <h2>Prospections</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Société</th>
                        <th>Mission</th>
                        <th>Progrès</th>
                    </tr>
                </thead>
                <tbody>
                {% for mission in prospections %}
                    <tr>
                        <td>{{ mission.societe.nom }}</td>
                        <td>{{ mission.titre }}</td>
                        <td> # </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="13">Aucune information trouvée</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div> <!-- /col-4 -->
        <!-- ENQUETE -->
        <div class="col-md-4">
            <h2>Enquêtes</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Société</th>
                        <th>Mission</th>
                        <th>Progrès</th>
                    </tr>
                </thead>
                <tbody>
                {% for mission in enquetes %}
                    <tr>
                        <td>{{ mission.societe.nom }}</td>
                        <td>{{ mission.titre }}</td>
                        <td> # </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="13">Aucune information trouvée</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div> <!-- /col-4 -->
    </div> <!-- /row -->
{% endblock %}

templates/missions/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Missions{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center"><a class="btn btn-lg btn-bleu my-2 mx-auto" href="{{ path('app_missions_actuelles') }}"><i class="fa-solid fa-arrow-left"></i> Retour</a></div>
    <h1>Mission {{ mission.titre }}</h1>
    DU {{ mission.dateDebut|date('d-m-Y') }} au {{ mission.dateFin|date('d-m-Y') }}
    <h2>Une mission confiée par {{ mission.societe.nom }} </h2>
    <p>
        Mettre l'image et lien balise img{{ mission.societe.logo }}
        </br>
        Ville: {{ mission.societe.ville }} </br>
        Téléphone: {{ mission.societe.tel }} </br>
        Contact {{ mission.societe.nomContact }} </br>
        {{ mission.societe.commentaires }}
    </p>
    <p>
        <h4> SCRIPT </h4>
        {{ mission.societe.nom}} {{ user.prenom }}, bonjour </br>
        {{ mission.script }} </br>
        {{ mission.commentaires }}
    </p>



    <a href="{{ path('app_missions_actuelles') }}" class="btn btn-lg btn-bleu d-grid gap-2 col-6 mx-auto my-2">Retour missions</a>
{% endblock %}

templates/missions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit{% endblock %}

{% block body %}
    <h1>Modifier une mission</h1>

    {{ include('_partials/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    <div class="row col-md-6 mx-auto">
        <div class="d-flex justify-content-center col-md-4 mx-auto d-grid gap-2">
            <a href="{{ path('app_statuts_index') }}" class="btn btn-lg btn-orange m-100" target="_blank">
                <i class="fa-solid fa-magnifying-glass"></i> 
                Les statuts
            </a>
        </div>
        <div class="d-flex justify-content-center col-md-4 mx-auto d-grid gap-2">
            <a href="{{ path('app_prerempli_index') }}" class="btn btn-lg btn-orange" target="_blank"><i class="fa-solid fa-magnifying-glass"></i> Les pré-remplis</a>
        </div>
        <div class="d-flex justify-content-center col-md-4 mx-auto d-grid gap-2">
            <a href="{{ path('app_champs_index') }}" class="btn btn-lg btn-orange" target="_blank"><i class="fa-solid fa-magnifying-glass"></i> Les champs</a>
        </div>
    </div>

    <a href="{{ path('app_missions_index') }}" class="btn btn-lg btn-bleu d-grid gap-2 col-6 mx-auto my-2">Retour à la liste des missions</a>

    {{ include('missions/_delete_form.html.twig') }}
{% endblock %}

templates/missions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Missions{% endblock %}

{% block body %}
    <h1 class="text-center">Toutes les missions</h1>
    <a href="{{ path('app_missions_new') }}" class="btn btn-lg btn-green d-grid gap-2 col-6 mx-auto my-2">Créer une nouvelle mission</a>
    <table class="table">
        <thead>
            <tr>
                <th>Société</th>
                <th>Titre</th>
                <th>Type</th>
                <th>Début</th>
                <th>Fin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mission in missions %}
            <tr style="background-color:{{mission.type.color}};">
                <td>{{ mission.societe.nom }}</td>
                <td>{{ mission.titre }}</td>
                <td>{{ mission.type.type }}</td>
                <td>{{ mission.dateDebut|date('d-m-Y') }}</td>
                <td>{{ mission.dateFin|date('d-m-Y') }}</td>
                {# <td>
                {% for champ in mission.champs %}
                    {{ champ.label }}
                {% endfor %}
                </td> #}
                <td>
                    <a href="{{ path('app_missions_show', {'id': mission.id}) }}" class="btn btn-green"><i class="fa-solid fa-magnifying-glass"></i> Voir plus</a>
                    <a href="{{ path('app_missions_edit', {'id': mission.id}) }}" class="btn btn-bleu">Modifier</a>
                    <a href="{{ path('app_missions_duplicate', {'id': mission.id}) }}" class="btn btn-orange">Dupliquer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">Aucune information trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/missions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}create{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        <a class="btn btn-lg btn-bleu my-2 mx-auto" href="{{ path('app_missions_index') }}"><i class="fa-solid fa-arrow-left"></i> Retour</a>
    </div>
    <h1 class="text-center">Nouvelle mission</h1>

    {{ include('_partials/_form.html.twig') }}
    <div class="row col-md-6 mx-auto">
        <div class="d-flex justify-content-center col-md-4 mx-auto d-grid gap-2">
            <a href="{{ path('app_statuts_index') }}" class="btn btn-lg btn-bleu m-100" target="_blank">
                <i class="fa-solid fa-magnifying-glass"></i> 
                Les statuts
            </a>
        </div>
        <div class="d-flex justify-content-center col-md-4 mx-auto d-grid gap-2">
            <a href="{{ path('app_prerempli_index') }}" class="btn btn-lg btn-bleu" target="_blank"><i class="fa-solid fa-magnifying-glass"></i> Les pré-remplis</a>
        </div>
        <div class="d-flex justify-content-center col-md-4 mx-auto d-grid gap-2">
            <a href="{{ path('app_champs_index') }}" class="btn btn-lg btn-bleu" target="_blank"><i class="fa-solid fa-magnifying-glass"></i> Les champs</a>
        </div>
    </div>
{% endblock %}

templates/missions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Missions{% endblock %}

{% block body %}
    <h1>Mission {{ mission.titre }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mission.id }}</td>
            </tr>
            <tr>
                <th>Société cliente</th>
                <td>{{ mission.societe.nom }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ mission.titre }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ mission.type.type }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ mission.dateDebut|date('Y-m-d') }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ mission.dateFin|date('Y-m-d') }}</td>
            </tr>
            <tr>
                <th>Script</th>
                <td>{{ mission.script }}</td>
            </tr>
            <tr>
                <th>Commentaires</th>
                <td>{{ mission.commentaires }}</td>
            </tr>
            <tr>
                <th>Email_rdv_client_text</th>
                <td>{{ mission.emailRdvClientText }}</td>
            </tr>
            <tr>
                <th>Email_rdv_prospect_text</th>
                <td>{{ mission.emailRdvProspectText }}</td>
            </tr>
            <tr>
                <th>Champs</th>
                <td>
                {% for champ in mission.champs %}
                    {{ champ.label }}
                {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Fichier</th>
                <td>{{ mission.fichier }}</td>
            </tr>
            <tr>
                <th>Statuts</th>
                <td>
                {% for statut in mission.statuts %}
                    {{ statut.type }}
                {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Pré-remplis</th>
                <td>
                {% for prerempli in mission.preremplis %}
                    {{ prerempli.texte }}
                {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_missions_index') }}" class="btn btn-lg btn-bleu d-grid gap-2 col-6 mx-auto my-2">Retour à la liste des missions</a>
    <a href="{{ path('app_missions_edit', {'id': mission.id}) }}" class="btn btn-lg btn-green d-grid gap-2 col-6 mx-auto my-2">Modifier</a>
    {{ include('missions/_delete_form.html.twig') }}
{% endblock %}