src/Entity/Champs.php
<?php

namespace App\Entity;

use App\Repository\ChampsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChampsRepository::class)]
class Champs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_champ = null;

    #[ORM\Column(length: 255)]
    private ?string $label = null;

    #[ORM\Column(length: 255)]
    private ?string $type_champ = null;

    #[ORM\Column]
    private ?bool $nullable = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $extras = null;

    #[ORM\Column(nullable: true)]
    private ?bool $visibleForm = null;

    #[ORM\Column(nullable: true)]
    private ?bool $modifiableClient = null;

    #[ORM\ManyToMany(targetEntity: Missions::class, mappedBy: 'champs')]
    private Collection $missions;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $position = null;

    #[ORM\Column(nullable: true)]
    private ?bool $triable = null;

    #[ORM\Column(nullable: true)]
    private ?bool $obligatoire = null;

    #[ORM\Column(nullable: true)]
    private ?bool $multiple = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $valueMultiple = null;

    public function __construct()
    {
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomChamp(): ?string
    {
        return $this->nom_champ;
    }

    public function setNomChamp(string $nom_champ): static
    {
        $this->nom_champ = $nom_champ;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): static
    {
        $this->label = $label;

        return $this;
    }

    public function getTypeChamp(): ?string
    {
        return $this->type_champ;
    }

    public function setTypeChamp(string $type_champ): static
    {
        $this->type_champ = $type_champ;

        return $this;
    }

    public function isNullable(): ?bool
    {
        return $this->nullable;
    }

    public function setNullable(bool $nullable): static
    {
        $this->nullable = $nullable;

        return $this;
    }

    public function getExtras(): ?string
    {
        return $this->extras;
    }

    public function setExtras(?string $extras): static
    {
        $this->extras = $extras;

        return $this;
    }

    public function isVisibleForm(): ?bool
    {
        return $this->visibleForm;
    }

    public function setVisibleForm(bool $visibleForm): static
    {
        $this->visibleForm = $visibleForm;

        return $this;
    }

    public function isModifiableClient(): ?bool
    {
        return $this->modifiableClient;
    }

    public function setModifiableClient(bool $modifiableClient): static
    {
        $this->modifiableClient = $modifiableClient;

        return $this;
    }

    /**
     * @return Collection<int, Missions>
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Missions $mission): static
    {
        if (!$this->missions->contains($mission)) {
            $this->missions->add($mission);
            $mission->addChamp($this);
        }

        return $this;
    }

    public function removeMission(Missions $mission): static
    {
        if ($this->missions->removeElement($mission)) {
            $mission->removeChamp($this);
        }

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(?string $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function isTriable(): ?bool
    {
        return $this->triable;
    }

    public function setTriable(?bool $triable): static
    {
        $this->triable = $triable;

        return $this;
    }

    public function isObligatoire(): ?bool
    {
        return $this->obligatoire;
    }

    public function setObligatoire(?bool $obligatoire): static
    {
        $this->obligatoire = $obligatoire;

        return $this;
    }

    public function isMultiple(): ?bool
    {
        return $this->multiple;
    }

    public function setMultiple(?bool $multiple): static
    {
        $this->multiple = $multiple;

        return $this;
    }

    public function getValueMultiple(): ?string
    {
        return $this->valueMultiple;
    }

    public function setValueMultiple(?string $valueMultiple): static
    {
        $this->valueMultiple = $valueMultiple;

        return $this;
    }
}

src/Form/ChampsType.php
<?php

namespace App\Form;

use App\Entity\Champs;
use App\Entity\Missions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChampsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_champ')
            ->add('label')
            ->add('type_champ')
            ->add('nullable')
            ->add('extras')
            ->add('visibleForm')
            ->add('modifiableClient')
            ->add('position')
            ->add('triable')
            ->add('obligatoire')
            ->add('multiple')
            ->add('valueMultiple')
            ->add('missions', EntityType::class, [
                'class'=>Missions::class,
                'choice_label'=>'titre',
                'multiple' => true,
                'expanded' => true,
                'label' => 'Missions ayant ce champ',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Champs::class,
        ]);
    }
}

src/Controller/ChampsController.php
<?php

namespace App\Controller;

use App\Entity\Champs;
use App\Form\ChampsType;
use App\Repository\ChampsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/champs')]
class ChampsController extends AbstractController
{
    #[Route('/', name: 'app_champs_index', methods: ['GET'])]
    public function index(ChampsRepository $champsRepository): Response
    {
        return $this->render('champs/index.html.twig', [
            'champs' => $champsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_champs_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ChampsRepository $champsRepository): Response
    {
        $champ = new Champs();
        $form = $this->createForm(ChampsType::class, $champ);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $champsRepository->save($champ, true);

            return $this->redirectToRoute('app_champs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('champs/new.html.twig', [
            'champ' => $champ,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_champs_show', methods: ['GET'])]
    public function show(Champs $champ): Response
    {
        return $this->render('champs/show.html.twig', [
            'champ' => $champ,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_champs_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Champs $champ, ChampsRepository $champsRepository): Response
    {
        $form = $this->createForm(ChampsType::class, $champ);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $champsRepository->save($champ, true);

            return $this->redirectToRoute('app_champs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('champs/edit.html.twig', [
            'champ' => $champ,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_champs_delete', methods: ['POST'])]
    public function delete(Request $request, Champs $champ, ChampsRepository $champsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$champ->getId(), $request->request->get('_token'))) {
            $champsRepository->remove($champ, true);
        }

        return $this->redirectToRoute('app_champs_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/champs/_delete_form.html.twig
<form method="post" action="{{ path('app_champs_delete', {'id': champ.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer ce champ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ champ.id) }}">
    <button  class="btn btn-lg btn-violet d-grid gap-2 col-6 mx-auto">Supprimer ce champ</button>
</form>

templates/champs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Champs{% endblock %}

{% block body %}
    <h1 class="text-center">Modifier un champ</h1>

    {{ include('_partials/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('app_champs_index') }}" class="btn btn-lg btn-bleu d-grid gap-2 col-6 mx-auto my-2">Retour à la liste</a>

    {{ include('champs/_delete_form.html.twig') }}
{% endblock %}

templates/champs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Champs index{% endblock %}

{% block body %}
    <h1>Tous les champs pré-enregistrés</h1>
    <a href="{{ path('app_champs_new') }}" class="btn btn-lg btn-green d-grid gap-2 col-6 mx-auto my-2">Nouveau champ standard</a>

    <table class="table">
        <thead>
            <tr>
                <th>Nom_champ</th>
                <th>Label</th>
                <th>Type_champ</th>
                <th>Nullable</th>
                <th>Extras</th>
                <th>VisibleForm</th>
                <th>ModifiableClient</th>
                <th>Position</th>
                <th>Triable</th>
                <th>Obligatoire</th>
                <th>Multiple</th>
                <th>ValueMultiple</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for champ in champs %}
            <tr>
                <td>{{ champ.nomChamp }}</td>
                <td>{{ champ.label }}</td>
                <td>{{ champ.typeChamp }}</td>
                <td>{{ champ.nullable ? 'Yes' : 'No' }}</td>
                <td>{{ champ.extras }}</td>
                <td>{{ champ.visibleForm ? 'Yes' : 'No' }}</td>
                <td>{{ champ.modifiableClient ? 'Yes' : 'No' }}</td>
                <td>{{ champ.position }}</td>
                <td>{{ champ.triable ? 'Yes' : 'No' }}</td>
                <td>{{ champ.obligatoire ? 'Yes' : 'No' }}</td>
                <td>{{ champ.multiple ? 'Yes' : 'No' }}</td>
                <td>{{ champ.valueMultiple }}</td>
                <td>
                    <a href="{{ path('app_champs_show', {'id': champ.id}) }}" class="btn btn-green"><i class="fa-solid fa-magnifying-glass"></i> Voir plus</a>
                    <a href="{{ path('app_champs_edit', {'id': champ.id}) }}" class="btn btn-bleu">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/champs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Champs{% endblock %}

{% block body %}
    <h1>Create new Champs</h1>

    {{ include('_partials/_form.html.twig') }}

    <a href="{{ path('app_champs_index') }}">back to list</a>
{% endblock %}

templates/champs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Champs{% endblock %}

{% block body %}
    <h1>Champs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ champ.id }}</td>
            </tr>
            <tr>
                <th>Nom_champ</th>
                <td>{{ champ.nomChamp }}</td>
            </tr>
            <tr>
                <th>Label</th>
                <td>{{ champ.label }}</td>
            </tr>
            <tr>
                <th>Type_champ</th>
                <td>{{ champ.typeChamp }}</td>
            </tr>
            <tr>
                <th>Nullable</th>
                <td>{{ champ.nullable ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Extras</th>
                <td>{{ champ.extras }}</td>
            </tr>
            <tr>
                <th>VisibleForm</th>
                <td>{{ champ.visibleForm ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>ModifiableClient</th>
                <td>{{ champ.modifiableClient ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Position</th>
                <td>{{ champ.position }}</td>
            </tr>
            <tr>
                <th>Triable</th>
                <td>{{ champ.triable ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Obligatoire</th>
                <td>{{ champ.obligatoire ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Multiple</th>
                <td>{{ champ.multiple ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>ValueMultiple</th>
                <td>{{ champ.valueMultiple }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_champs_index') }}" class="btn btn-lg btn-bleu d-grid gap-2 col-6 mx-auto my-2">Retour à la liste des champs pré-enregistrés</a>
    <a href="{{ path('app_champs_edit', {'id': champ.id}) }}" class="btn btn-lg btn-green d-grid gap-2 col-6 mx-auto my-2">Modifier</a>
    {{ include('champs/_delete_form.html.twig') }}
    
{% endblock %}